### ISSUE TITLE
About the shell script

### ISSUE THREAD

**Issue by Yongxuanzhang** [cmhungsteve/TA3N#10]
Hi @cmhungsteve ,

Thanks for sharing the codes. I wonder if the script_train_val file is correct or not. I try to run it but face some errors. (e.g. error: argument --pred_normalize: expected one argument) It seems that this version misses some arguments. 

Best.

**Comment by cmhungsteve** [comment]
It seems that I forgot to remove some arguments that I don't use.
Can you try again?
If there are still errors, can you copy and paste all the error messages here?
Thank you.

**Comment by Yongxuanzhang** [comment]
Hi,
Thanks for your kind reply!
2) I'm not sure about it because I still face other errors on file paths. 
I wonder if I can directly run the main.py file after changing the arguments in "opts" and keeping them consistent with the script? 
2) Another question, is the best score the prediction accuracy?
For example,
"Testing Results: Prec@1 8.333 Prec@5 41.667 Loss 2.54561"
What's the meaning of Prec@1 and Prec@5?

**Comment by cmhungsteve** [comment]
1. Yes, you can, but there are lots of arguments, so you may need to check `opt.py`.
2. you can ignore Prec@5, Prec@1 here means the accuracy.

**Comment by Yongxuanzhang** [comment]
Thank you very much!
