### ISSUE TITLE
T-SNE visualization

### ISSUE THREAD

**Issue by lerndeep** [cmhungsteve/TA3N#14]
I want to visualized data after a training network. could you provide an idea of how can I visualize source and target data after training for comparison of data alignment way? I read your paper you are using T-SNE for visualization but I have no idea how can I use T-SNE after training finished. I prepared T-SNE before training source and target data but after training, I have a problem with visualization.

**Comment by cmhungsteve** [comment]
I use tensorboard-X.
You just need to feed data and domain labels to the embedding API of tensorboard, then you can generate the t-SNE visualization.
