### ISSUE TITLE
output feature

### ISSUE THREAD

**Issue by wzr113** [cmhungsteve/TA3N#15]
Hello, thanks for your great job, I want to ask if the code could output the feature processed?and how to visulize the feature processed and unprocessed like the picture in your paper?

**Comment by cmhungsteve** [comment]
I use tensorboardX.
You use need to use the option `tensorboard`, and then during training, the code will generate tensorboard files for you to visualize (you need to open tensorboard API via browser)
for more detail, please check: https://github.com/lanpa/tensorboardX

Thanks

**Comment by YUunicorn9** [comment]
Hello,thanks for your reply. I use the tensorboardX to visualize feature, but the effect is not as good as that in your paper. How can I improve visualization? Are there anything need to set when visualize?

**Comment by cmhungsteve** [comment]
There are some parameters that you need to tune t-SNE, like perplexity, iterations, etc.
You can tune that in the browser

**Comment by YUunicorn9** [comment]
Thank you very much! Furthermore, I want to know if I can only visualize features of one class? Do you have any suggestions? Is it just to revise the code "writer.add_embedding(feat_source_display, metadata=label_source_display.data, global_step=n_iter_train, tag='train_source')"

**Comment by cmhungsteve** [comment]
you mainly modify `feat_source_display` and `label_source_display`.
However, I am not sure if it's a good idea to visualize only one class. 
Usually, people visualize at least two classes to see how your model clusters data well.
