### ISSUE TITLE
Do we need parallel data for this to train properly?

### ISSUE THREAD

**Issue by jlim13** [cmhungsteve/TA3N#17]
Do we need all of the classes for the source and target domains to match?
Also, when training, are the classes aligned for every mini batch?

**Comment by cmhungsteve** [comment]
For each epoch, we need all the classes from source and target domains, but for each mini-batch, it's not necessary.

**Comment by jlim13** [comment]
thanks for the quick response! 

I see. So I am doing some work on video domain adaptation (video captioning) and want to compare my method to yours. There is no overlap between the classes of the source and target domain (i.e. the sentences are all different). There doesn't seem to be a straightforward way to extend ta3n to settings when the source and target domain don't share the same labels. Am I correct or did I miss something in the paper?

Thanks!

**Comment by cmhungsteve** [comment]
Yes, you are right.
That's what I think.
