### ISSUE TITLE
Input data links are expired

### ISSUE THREAD

**Issue by tsuyoshily** [cmhungsteve/TA3N#19]
HI,
I'm terribly sorry to disturb you again, but Input data links are expired.
Please update the URL.

**Comment by cmhungsteve** [comment]
Yeah, there are some issues happening for the links.
I will try to fix them before this weekend or next week.
Thank you.

**Comment by cmhungsteve** [comment]
The links are all updated.
For the Kinetics-Gameplay dataset, please fill the form again.
Thank you.

**Comment by tsuyoshily** [comment]
Thanks for the quick reply and support.

**Comment by stefanxinhong** [comment]
I have no access to the  validation list of UCF101 in UCF-HMDB_full (dropbox link)
