### ISSUE TITLE
Question about the training details?

### ISSUE THREAD

**Issue by xiaosean** [cmhungsteve/TA3N#2]
Nice work!
Thanks for your sharing code!

I am interested in this task,
I want to know some training detail.
- Which GPUs are you using, and how many GPUs are you using?
- Using your setting, I am curious about your UCF -> HMDE and HMDE -> UCF experiments detail
> How long do you train on these experiments(hours/days)?

**Comment by cmhungsteve** [comment]
Hello

I use two GeForce GTX TITAN X GPUs with 12GB memory for each.
The training is less an hour.

**Comment by xiaosean** [comment]
Thanks for your reply!!
