### ISSUE TITLE
argument_modality: invalid choice

### ISSUE THREAD

**Issue by kerenartiaga** [cmhungsteve/TA3N#29]
Hi, I used the pre-extracted features provided and manually edited the paths in the data list files. I am sure my paths are correct but I am getting the following error when running the script_train_val.sh:

main.py: error: argument modality: invalid choice: 'data/classInd_ucf_olympic.txt' (choose from 'RGB', 'Flow', 'RGBDiff', 'RGBDiff2', 'RGBDiffplus')  .

 Do you have any insight as to where I did it wrong?  Thank you in advance.

**Comment by cmhungsteve** [comment]
I revise the script a little bit.
please try again.

**Comment by kerenartiaga** [comment]
I tried the revised script. The new error says: 

[WinError 206] The filename or extension is too long: 'action-experiments/Testexp-SGD-share_params_Y-lr_3e-2-bS_128_74/hmdb_ucf-5seg-disDA_none-alpha_0-advDA_RevGrad-beta_0.75_0.75_0.5-useBN_none-addlossDA_attentive_entropy-gamma_0.003-ensDA_none-mu_0-useAttn_TransAttn-n_attn_1

**Comment by cmhungsteve** [comment]
I guess it's related to Windows OS. Windows has some limitation about the file name

**Comment by kerenartiaga** [comment]
I enabled long filename support and it starts training now. Thanks a lot.
