### ISSUE TITLE
question about Target Entropy

### ISSUE THREAD

**Issue by kerenartiaga** [cmhungsteve/TA3N#51]
Hello Sir,

I have a question about add_loss_DA configuration. I have read the TA3N paper, but the target entropy is not mentioned, may I ask where can I find more information about it? Thank you in advance.

**Comment by cmhungsteve** [comment]
You can ignore that. 
That's just an option that I tried before, but the performance was not good.
You can just follow the arguments in the script.
Thanks.

**Comment by kerenartiaga** [comment]
Alright, thank you
