### ISSUE TITLE
Question about Frame Relation when  use_target is set to "none"

### ISSUE THREAD

**Issue by kerenartiaga** [cmhungsteve/TA3N#52]
Hello Sir,

Sorry I forgot to ask this in my previous issue:
When use_target is set to "none", does frame-relation still work?

Thank you

**Comment by cmhungsteve** [comment]
If you set "frame_aggregation=trn-m", it means that you are using "frame-relation".
If you set "frame_aggregation=avgpool", it means that you're not using "frame-relation".
"use_target" is not related.

**Comment by kerenartiaga** [comment]
I see. When using avgpool, do we align frames one by one instead of by relation?

**Comment by cmhungsteve** [comment]
No, since we are working on the classification task, we just evenly sample frames and average them to get the final output prediction.
The frame indices between different videos are not aligned since that part is not critical for the classification task.
