### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by DanZhang123** [cmhungsteve/TA3N#8]
Why is formula 7 a minus sign instead of a plus sign? Why not add more weight to the ones that are hard to distinguish.

I am looking forward to your answer. Thank you very much!

**Comment by cmhungsteve** [comment]
After we assign the attention weights, we will perform DA on all the attended data. Since we want our DA to focus more on the ones easy to distinguish in terms of domains (i.e. contribute more on to the overall domain shift), we use the minus sign here.

Hope that answers your question
